version: '3.8'

services:
  reactjs-ui:
    image: node:20.6-alpine3.17
    container_name: reactjs-ui
    working_dir: /app
    command:
      - /bin/sh
      - -c
      - |
        tail -F /dev/null
    # user: '1000:1000'
    volumes:
      - /app/node_modules
      - ./reactjs-ui:/app
    ports:
      - '3000:3000'
      - '4000:4000'
    restart: unless-stopped
