FROM nginx:1.23.2

WORKDIR /react

# https://github.com/nodesource/distributions#debinstall
RUN curl -fsSL https://deb.nodesource.com/setup_19.x | bash -
RUN apt-get install -y nodejs

COPY ./reactjs/portfolio/package*.json ./

# Otherwise compatibility error
RUN npm install --legacy-peer-deps

# Copy the source code
COPY ./reactjs/portfolio/ .

# Build the React application
RUN npm run build

# Copy the Nginx configuration file
RUN \cp reactjs-nginx.conf /etc/nginx/conf.d/default.conf

# Copy the React application
RUN rm -rf /usr/share/nginx/html/*
RUN cp -a build/. /usr/share/nginx/html

RUN rm -rf /react/*